spring:
  # H2 메모리 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:scheduledb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 웹 콘솔 활성화 (데이터 확인용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 애플리케이션 시작 시 테이블 생성, 종료 시 삭제
    show-sql: true           # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true     # SQL 포맷팅
        dialect: org.hibernate.dialect.H2Dialect

# 로깅 설정
logging:
  level:
    com.example.gagso.Schedule: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 포트
server:
  port: 8080